/*
 * NudmUEAU
 *
 * UDM UE Authentication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ueauthentication

import (
	"free5gc/lib/http_wrapper"
	"free5gc/lib/openapi/models"
	"free5gc/src/udm/logger"
	"free5gc/src/udm/handler"
	udm_message "free5gc/src/udm/handler/message"
	"github.com/gin-gonic/gin"
	// "fmt"
)

// GenerateAuthData - Generate authentication data for the UE
func GenerateAuthData(c *gin.Context) {
	var authInfoReq models.AuthenticationInfoRequest
	err := c.ShouldBindJSON(&authInfoReq)
	if err != nil {
		logger.UeauLog.Errorln(err)
	}

	req := http_wrapper.NewRequest(c.Request, authInfoReq)
	req.Params["supiOrSuci"] = c.Param("supiOrSuci")

	handlerMsg := udm_message.NewHandlerMessage(udm_message.EventGenerateAuthData, req)
	handler.SendMessage(handlerMsg)
	rsp := <-handlerMsg.ResponseChan

	HTTPResponse := rsp.HTTPResponse
	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
	return
}
