/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package subscriberdatamanagement_test

import (
	"context"
	"fmt"
	"free5gc/lib/http2_util"
	Nudm_SDM_Client "free5gc/lib/openapi/Nudm_SubscriberDataManagement"
	"free5gc/lib/path_util"
	udm_context "free5gc/src/udm/context"
	"free5gc/src/udm/logger"
	"free5gc/src/udm/handler"
	"net/http"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/assert"
)

// UnsubscribeForSharedData - unsubscribe from notifications for shared data
func TestUnsubscribeForSharedData(t *testing.T) {

	go func() { // udm server
		router := gin.Default()

		router.DELETE("/nudm-sdm/v1/shared-data-subscriptions/:subsId", func(c *gin.Context) {
			subscriptionId := c.Param("subscriptionId")
			fmt.Println("==========UnsubscribeForSharedData - unsubscribe from notifications for shared data==========")
			fmt.Println("subscriptionId: ", subscriptionId)
			c.JSON(http.StatusNoContent, gin.H{})
		})

		udmLogPath := path_util.Gofree5gcPath("free5gc/udmsslkey.log")
		udmPemPath := path_util.Gofree5gcPath("free5gc/support/TLS/udm.pem")
		udmKeyPath := path_util.Gofree5gcPath("free5gc/support/TLS/udm.key")

		server, err := http2_util.NewServer(":29503", udmLogPath, router)
		if err == nil && server != nil {
			logger.InitLog.Infoln(server.ListenAndServeTLS(udmPemPath, udmKeyPath))
			assert.True(t, err == nil)
		}
	}()

	udm_context.TestInit()
	go handler.Handle()

	udm_context.Init()
	cfg := Nudm_SDM_Client.NewConfiguration()
	cfg.SetBasePath("https://localhost:29503")
	clientAPI := Nudm_SDM_Client.NewAPIClient(cfg)

	subscriptionId := "SDM1234"
	resp, err := clientAPI.SubscriptionDeletionForSharedDataApi.UnsubscribeForSharedData(context.TODO(), subscriptionId)
	if err != nil {
		fmt.Println(err.Error())
	} else {
		fmt.Println("resp: ", resp)
	}
}
