/*
 * Nudm_PP
 *
 * Nudm Parameter Provision Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package parameterprovision

import (
	"free5gc/lib/http_wrapper"
	"free5gc/lib/openapi/models"
	"free5gc/src/udm/handler"
	udm_message "free5gc/src/udm/handler/message"
	"free5gc/src/udm/logger"
	"github.com/gin-gonic/gin"
	"net/http"
)

// Update - provision parameters
func Update(c *gin.Context) {

	var ppDataReq models.PpData
	err := c.ShouldBindJSON(&ppDataReq)
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		logger.PpLop.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := http_wrapper.NewRequest(c.Request, ppDataReq)
	req.Params["gspi"] = c.Params.ByName("gpsi")

	handleMsg := udm_message.NewHandlerMessage(udm_message.EventUpdate, req)
	handler.SendMessage(handleMsg)

	rsp := <-handleMsg.ResponseChan
	HTTPResponse := rsp.HTTPResponse
	c.JSON(HTTPResponse.Status, HTTPResponse.Body)

}
